### PR TITLE
KeyInContextHasNoValueError, KeyNotInContextError

### PR DESCRIPTION
**Pull request by 345thomas**
- use new pypyr error types for context validation errors
- unit tests
- version bump

### CODE REVIEW

**Comment by 345thomas** [comment]
ahem, use new pypyr error types for context validation errors

**Comment by 345andrew** [comment]
Yesbut....none of the code files were changed.  Although the underlying core components are raising those errors the Slack module is unchanged.

**Comment by 345thomas** [comment]
aaah! you're right! soz, for some reason I thought the step itself was doing something w the err - you'd think the man who requested the pull would know what's in his own PR, eh :-|

**Comment by 345thomas** [comment]
a

**Pull request merged**
